---
#agent_fname: "../../../models/walk_ref_osim_AsyncSoftActorCritic_3.95.asac"
init_data_fname:
pretrained_policy: #"../../../models/walk_ref_osim_AsyncSoftActorCritic_5.90.asac"
collect_data: false
log_mode: full
target_entropy: -70
seed: 123456
lr: 0.003
soft_tau: 0.005
num_updates_per_step: 10
soft_update_period: 1
gamma: 0.96

action_penalty: 0.01
noise:
  type: "state_action" # ou, none
  max_sigma: 0.3
  hidden_dim:
    - 128
    - 64

#  noise_init_level: 0.3
#  noise_decay: 0.995
#  noise_min: 0.05


env:
  env_id: ref_masked_dtw_we_vtl # vtl_base, dtw_we_vtl, masked_dtw_we_vtl
  random_offset: true
  speaker_fname: "C:/Study/SpeechAcquisitionModel/src/VTL/JD2.speaker"
  lib_path: "C:/Study/SpeechAcquisitionModel/src/VTL/VocalTractLab2.dll"
  selected_reference_state:
    - "ACOUSTICS"
    - "HX"
    - "HY"
    - "JX"
    - "JA"
    - "LP"
    - "LD"
    - "VS"
    - "VO"
    - "WC"
    - "TCX"
    - "TCY"
    - "TTX"
    - "TTY"
    - "TBX"
    - "TBY"
    - "TRX"
    - "TRY"
    - "TS1"
    - "TS2"
    - "TS3"
    - "TS4"
    - "MA1"
    - "MA2"
    - "MA3"
  selected_actions:
    - "HX"
    - "HY"
    - "JX"
    - "JA"
    - "LP"
    - "LD"
    - "VS"
    - "VO"
    - "WC"
    - "TCX"
    - "TCY"
    - "TTX"
    - "TTY"
    - "TBX"
    - "TBY"
    - "TRX"
    - "TRY"
    - "TS1"
    - "TS2"
    - "TS3"
    - "TS4"
    - "MA1"
    - "MA2"
    - "MA3"
  norm_observation: true
  norm_action: true
  num_workers: 2
  visualize: true

  timestep: 40 # in ms
  max_episode_duration: 1000 # in ms
  showControlPoints: True
  showCenterLine: False
  showCutVectors: True
  renderBothSides: False
  renderMode: 2

  audio_upper_bound: 1.0 # KEEP THIS AT 1.0 or maybe 2.0?
  preprocessing_params:
    name: AudioPreprocessorMFCCDeltaDelta
    numcep: 13
    winlen: 0.02
    winstep: 0.01
    sample_rate: 22050
    target_sample_rate: 8000

  preproc_net:
    config: "C:/Study/SpeechAcquisitionModel/models/soft_dtw_awe/model_16/config.yaml"
    preproc_net_fname: "C:/Study/SpeechAcquisitionModel/models/soft_dtw_awe/model_16/net_49000.pt"
    device: "cuda"
    output_dim: 16
  references:
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/a_i_1_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/a_i_2_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/a_i_3_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/a_i_4_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/a_a_1_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/a_a_2_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/a_a_3_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/a_a_4_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/a_u_1_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/a_u_2_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/a_u_3_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/a_u_4_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/a_o_1_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/a_o_2_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/a_o_3_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/a_o_4_1.pkl"

    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_i_1_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_i_2_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_i_3_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_i_4_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_a_1_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_a_2_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_a_3_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_a_4_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_u_1_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_u_2_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_u_3_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_u_4_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_o_1_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_o_2_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_o_3_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_o_4_1.pkl"

    - "C:/Study/SpeechAcquisitionModel/data/reference_data/u_i_1_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/u_i_2_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/u_i_3_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/u_i_4_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/u_a_1_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/u_a_2_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/u_a_3_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/u_a_4_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/u_u_1_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/u_u_2_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/u_u_3_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/u_u_4_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/u_o_1_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/u_o_2_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/u_o_3_1.pkl"
    - "C:/Study/SpeechAcquisitionModel/data/reference_data/u_o_4_1.pkl"

#    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_i_1.pkl"
#    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_i_2.pkl"
#    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_i_3.pkl"
#    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_i_4.pkl"
#    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_a_1.pkl"
#    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_a_2.pkl"
#    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_a_3.pkl"
#    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_a_4.pkl"
#    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_u_1.pkl"
#    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_u_2.pkl"
#    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_u_3.pkl"
#    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_u_4.pkl"
#    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_o_1.pkl"
#    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_o_2.pkl"
#    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_o_3.pkl"
#    - "C:/Study/SpeechAcquisitionModel/data/reference_data/i_o_4.pkl"
#
  distance:
#    name: 'soft-DTW'
#    open_end: True
#    dist: 'l1'

    name: 'dtwalign'
    open_end: True
    dist: 'minkowski'
    step_pattern: 'symmetric2'


train:
  max_steps: 3000000
  batch_size: 32
  sync_every: 200
  validate_every: 200
replay_buffer:
  size: 1000000
model_dynamics:
  hidden_dim:
  - 256
  - 256
  - 128
policy_network:
  hidden_dim:
  - 256
  - 256
