env:
  env_id: masked_dtw_we_vtl # vtl_base, dtw_we_vtl
  speaker_fname: "C:/Study/SpeechAcquisitionModel/src/VTL/JD2.speaker"
  lib_path: "C:/Study/SpeechAcquisitionModel/src/VTL/VocalTractLab2.dll"
  selected_actions:
    - "HX"
    - "HY"
    - "JX"
    - "JA"
    - "LP"
    - "LD"
#    - "VS"
#    - "VO"
#    - "WC"
#    - "TCX"
#    - "TCY"
#    - "TTX"
#    - "TTY"
#    - "TBX"
#    - "TBY"
#    - "TRX"
#    - "TRY"
#    - "TS1"
#    - "TS2"
#    - "TS3"
#    - "TS4"
#    - "MA1"
#    - "MA2"
#    - "MA3"
  norm_observation: true
  norm_action: false
  num_workers: 2
  visualize: True
  seed: 123456
  timestep: 40
  max_episode_duration: 1000
  showControlPoints: True
  showCenterLine: False
  showCutVectors: True
  renderBothSides: False
  renderMode: 2
  preprocessing_params:
    name: AudioPreprocessorMFCCDeltaDelta
    numcep: 13
    winlen: 0.02
    winstep: 0.01
    sample_rate: 22050
#    name: AudioPreprocessorMFCCDeltaDelta
#    numcep: 12
#    winlen: 0.02
#    winstep: 0.02
#    sample_rate: 22050

  preproc_net:
    preproc_net_fname: "C:/Study/SpeechAcquisitionModel/reports/seamise_net_10_25_2019_01_55_PM/net_0.4609375.net"
    device: "cuda"
    output_dim: 32
  references:
    - "C:/Study/SpeechAcquisitionModel/src/VTL/references/a_i.pkl"
#    - "C:/Study/SpeechAcquisitionModel/src/VTL/references/a_u.pkl"
#    - "C:/Study/SpeechAcquisitionModel/src/VTL/references/i_a_2.pkl"
  distance:
#    name: 'soft-DTW'
#    open_end: True
#    dist: 'l1'

    name: 'dtwalign'
    open_end: True
    dist: 'euclidean'
    step_pattern: 'typeIc'

